version: '3'

services:
  server_redis_database:
    image: redis:latest
    container_name: server_redis_database
    env_file:
      - ../.env_development
    volumes:
      - ./redis_data:/data
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"

  server_api:
    container_name: server_api
    build:
      context: ../api
      dockerfile: docker/Dockerfile.development
    env_file:
      - ../.env_development
    volumes:
      - ../api/routes:/srv/echo-at-time/routes
      - ../api/api.js:/srv/echo-at-time/api.js
      - ../utils:/srv/echo-at-time/utils
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"